clearWeaponCargoGlobal RedCrate;
clearWeaponCargoGlobal BlueCrate;
clearMagazineCargoGlobal BlueCrate;
clearMagazineCargoGlobal RedCrate;
clearBackpackCargoGlobal BlueCrate;
clearBackpackCargoGlobal RedCrate;
clearItemCargoGlobal RedCrate;
clearItemCargoGlobal BlueCrate;